on:
  push:
    branches:
      - main
  pull_request:
name: ci
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - run: pnpm install
      - run: pnpm lint
  release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          environment: prod
          wranglerVersion: "3.99.0"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
